Blog_Sports_I/urls.py
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='index.html')),
    path('accounts/account_logout', include('allauth.urls')),
    path('memberships/', include('apps.memberships.urls' ,namespace = "memberships")),
    path('posts/', include('apps.posts.urls', namespace = "posts")),
    path('daily_pick/', include('apps.daily_pick.urls', namespace = 'daily_picks')),
    path('hockey/', include('apps.hockey.urls', namespace = "hockey")),
    path('pro_hoops/', include('apps.pro_hoops.urls', namespace = "pro_hoops")),
    path('college_hoops/', include('apps.college_hoops.urls', namespace = "college_hoops")),
    path('baseball/', include('apps.baseball.urls', namespace = "MLB_baseball")),
]

apps/baseball/urls.py
from django.urls import path, re_path

from . views import(baseball_index, show_baseball_odds)

app_name = "baseball"

urlpatterns = [
    path( '', baseball_index , name = "mlb_schedule"),
    re_path(r'^show_baseball_odds/(?P<id>\d+)$', show_baseball_odds, name="show_baseball_odds"),

]

apps/hockey/urls.py
from django.urls import path, re_path

from . views import(hockey_index, show_hockey_odds)

app_name = "hockey"

urlpatterns = [
    path( '', hockey_index , name = "schedule"),
    re_path(r'^show_hockey_odds/(?P<id>\d+)$', show_hockey_odds, name="show_hockey_odds"),

]

apps/memberships/urls.py
from django.urls import path

from . views import (
    MembershipSelectView,
    PaymentView,
    updateTransactions,
    profile_view,
    cancelSubscription
)

app_name = 'memberships'


urlpatterns = [
    path('', MembershipSelectView.as_view(), name = 'select'),
    path('payment/', PaymentView, name = 'payment'),
    path('update-transactions/<subscription_id>/', updateTransactions, name = 'update-transactions'),
    path('profile/', profile_view, name='profile'),
    path('cancel/', cancelSubscription, name='cancel')
]

apps/posts/urls.py
from django.urls import path
from . views import(
    PostListView,
    PostDetailView
)

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name = 'list'),
    path('<slug>', PostDetailView.as_view(), name = 'detail'),
]

apps/pro_hoops/urls.py
from django.urls import path, re_path

from . views import(hoop_index, show_hoop_odds)

app_name = "pro_hoops"

urlpatterns = [
    path( '', hoop_index , name = "nba_schedule"),
    re_path(r'^show_hoop_odds/(?P<id>\d+)$', show_hoop_odds, name="show_hoop_odds"),

]

apps/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.urls import reverse
from apps.memberships.models import Membership, UserMembership




STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    allowed_memberships = models.ManyToManyField(Membership)
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

apps/posts/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse, HttpResponseRedirect
from .models import Post
from django.views.generic import ListView, DetailView, View
from apps.memberships.models import UserMembership, Membership, Subscription
from apps.daily_pick.models import DailyPick

class PostListView(ListView):
    model = Post


class PostDetailView(View):
    #model = Post
    def get (self, request, slug, *args, **kwargs):
        post_qs = Post.objects.filter(slug = slug)
        if post_qs.exists():
            post = post_qs.first()

        user_membership = UserMembership.objects.filter(user = request.user).first()
        user_membership_type = user_membership.membership.membership_type
        print(user_membership_type)
        post_allowed_mem_types = post.allowed_memberships.all()
        print(post_allowed_mem_types)
        context = {
            'object':None
        }

        if post_allowed_mem_types.filter(membership_type = user_membership_type).exists():
            context = {
                'object':post
            }


        return render(request, 'posts/post_detail.html', context)

apps/posts/templates/posts/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Sports Posts</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<style>
		#wrapper{
			background-color: #F8FAF0;
			width:100%;
			height: 700px;
			border-color: black;
			border-width: 8px;
			border-style: double;
		}
		p{
			font-size: 24px;
		}

	</style>
</head>
<body>

	{% include 'posts/messages.html' %}

	<div class="container">
		<ol class='breadcrumb'>
				<li><a href="{% url 'memberships:profile' %}">Profile</a></li>
				{% if user_subscription.active == True %}
				<li><a href={% url 'posts:list' %}>Posts</a></li>
				{% endif %}
				<li><a href="{% url 'baseball:mlb_schedule' %}">MLB</a></li>
				<li><a href="{% url 'pro_hoops:nba_schedule' %}">NBA</a></li>
				<li><a href="{% url 'college_hoops:ncaab_schedule' %}">NCAAB</a></li>
				<li><a href="{% url 'hockey:schedule' %}">NCAAF</a></li>
				<li><a href="{% url 'hockey:schedule' %}">NFL</a></li>
				<li><a href="{% url 'hockey:schedule' %}">NHL</a></li>

	        {% block post_detail_link %}

	        {% endblock %}

					{% if not request.user.is_authenticated %}
	        <li class='pull-right'><a href="{% url 'accounts:register' %}">Register</a></li>
	        <li class='pull-right'><a href="{% url 'accounts:login' %}">Login</a></li>
					{% else %}
	        <li class='pull-right'><a href="{% url 'memberships:select' %}">Memberships</a></li>
					<li class='pull-right'><a href="{% url 'account_logout' %}">Logout </a></li>
					{% endif %}
	    </ol>
	</div>
	<div id="wrapper">
	{% block content %}

	{% endblock content %}
</div>
	<script
  	src="https://code.jquery.com/jquery-3.3.1.js"
  	integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  	crossorigin="anonymous"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

apps/posts/templates/posts/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

apps/posts/templates/posts/post_detail.html
{% extends 'posts/base.html' %}

	{% block content %}
	<div class = "page-header">
		<center>
		<h1>The Sports Blog -- "Beat Your Bookie.Com"</h1>
		</center
		</div>
		<div class = "container" >
			{% if object is not None %}
				<h3>{{ object.title }}</h3>
					<ul>
						<li>{{ object.author }}</li>
						<li>{{ object.created_on }}</li>
					</ul><br>
						<center>
							<p>	{{ object.content }}</p>
						</center>

				{% else %}
					<center><h2>In order to read posts, please upgrade your membership!</h2></center>

			{% endif %}

		{% endblock content %}
		</div>

apps/posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}

  {% block content %}
  <div class = "container" >
    <h1>Post List Page</h1>
      {% for object in object_list %}
      <ul>
        <li><h2><a href="{{ object.get_absolute_url }}">{{ object }}</a></h2></li>
        </ul>
      {% endfor %}
  </div>
    {% endblock content %}