Blog_Sports_I/urls.py
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='index.html')),
    path('accounts/account_logout', include('allauth.urls')),
    path('memberships/', include('apps.memberships.urls' ,namespace = "memberships")),
    path('posts/', include('apps.posts.urls', namespace = "posts")),
    path('daily_pick/', include('apps.daily_pick.urls', namespace = 'daily_picks')),
    path('hockey/', include('apps.hockey.urls', namespace = "hockey")),
    path('pro_hoops/', include('apps.pro_hoops.urls', namespace = "pro_hoops")),
    path('college_hoops/', include('apps.college_hoops.urls', namespace = "college_hoops")),
    path('baseball/', include('apps.baseball.urls', namespace = "MLB_baseball")),
]

apps/memberships/urls.py
from django.urls import path

from . views import (
    MembershipSelectView,
    PaymentView,
    updateTransactions,
    profile_view,
    cancelSubscription
)

app_name = 'memberships'


urlpatterns = [
    path('', MembershipSelectView.as_view(), name = 'select'),
    path('payment/', PaymentView, name = 'payment'),
    path('update-transactions/<subscription_id>/', updateTransactions, name = 'update-transactions'),
    path('profile/', profile_view, name='profile'),
    path('cancel/', cancelSubscription, name='cancel')
]

apps/memberships/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from datetime import datetime

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your models here.

MEMBERSHIP_CHOICES = (
    ('Free', 'free'),
    ('Daily', 'dly'),
    ('Weekly', 'wkly'),
    ('Monthly', 'monthly'),

)


class Membership(models.Model):
    slug = models.SlugField()
    membership_type = models.CharField(choices = MEMBERSHIP_CHOICES, default = "Free", max_length = 30)
    description = models.TextField()
    price = models.IntegerField(default=6)
    stripe_plan_id = models.CharField(max_length = 40)

    def __str__(self):
        return self.membership_type

class UserMembership(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    stripe_customer_id = models.CharField(max_length = 40)
    membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null = True)

    def __str__(self):
        return self.user.username

def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
        if created:
            UserMembership.objects.get_or_create(user = instance)

        user_membership, created = UserMembership.objects.get_or_create(user = instance)

        if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
            new_customer_id = stripe.Customer.create(email = instance.email)
            free_membership = Membership.objects.get(membership_type='Free')
            user_membership.stripe_customer_id = new_customer_id['id']
            user_membership.membership = free_membership
            user_membership.save()

post_save.connect(post_save_usermembership_create, sender = settings.AUTH_USER_MODEL)


class Subscription(models.Model):
    user_membership = models.ForeignKey(UserMembership, on_delete = models.CASCADE)
    stripe_subscription_id = models.CharField(max_length = 40)
    active = models.BooleanField(default = True)

    def __str__(self):
        return self.user_membership.user.username

    @property
    def get_created_date(self):
        subscription = stripe.Subscription.retrieve(
            self.stripe_subscription_id)
        return datetime.fromtimestamp(subscription.created)

    @property
    def get_next_billing_date(self):
        subscription = stripe.Subscription.retrieve(
            self.stripe_subscription_id)
        return datetime.fromtimestamp(subscription.current_period_end)

apps/memberships/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.views.generic import ListView
from .models import Membership, UserMembership, Subscription
from apps.daily_pick.models import DailyPick
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime
import stripe
from django.contrib import auth
from django.contrib.auth.models import User
from dotenv import load_dotenv
...
load_dotenv()

def get_user_membership(request):
    user_membership_qs = UserMembership.objects.filter(user = request.user)
    print("*" *50)
    if user_membership_qs.exists():
        return user_membership_qs.first()
    return None

def get_user_subscription(request):
    user_subscription_qs = Subscription.objects.filter(
        user_membership = get_user_membership(request))
    if user_subscription_qs.exists():
        user_subscription = user_subscription_qs.first()
        return user_subscription
    return None

def get_selected_membership(request):
    membership_type = request.session['selected_membership_type']
    selected_membership_qs = Membership.objects.filter(
        membership_type = membership_type)
    if selected_membership_qs.exists():
        return selected_membership_qs.first()
    return None

def get_daily_pick(request):
    daily_pick_qs = DailyPick.objects.all()
    print(daily_pick_qs)
    if daily_pick_qs.exists():
        daily_pick = daily_pick_qs.first()
        #print(daily_pick)
    context = {
            'object':daily_pick
    }
    #print(context)
    return(context)



class MembershipSelectView(ListView):
    model = Membership

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        current_membership = get_user_membership(self.request)
        print(current_membership)
        context['current_membership'] = str(current_membership.membership)
        return context

    def post(self, request, **kwargs):
        selected_membership_type = request.POST.get('membership_type')
        user_membership = get_user_membership(request)
        user_subscription = get_user_subscription(request)

        selected_membership_qs = Membership.objects.filter(
            membership_type = selected_membership_type)
        if selected_membership_qs.exists():
            selected_membership = selected_membership_qs.first()


        if user_membership.membership == selected_membership:
            if user_subscription is not None:
                messages.info(request, "You already have this membership.")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        #assign to session
        request.session['selected_membership_type'] = selected_membership.membership_type

        return HttpResponseRedirect(reverse('memberships:payment'))

def PaymentView(request):
    user_membership = get_user_membership(request)
    selected_membership = get_selected_membership(request)
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == "POST":
        try:
            token = request.POST['stripeToken']
            customer = stripe.Customer.retrieve(user_membership.stripe_customer_id)
            customer.source = token # 4242424242424242
            customer.save()
            print("Saved HowdyDoody")

            subscription = stripe.Subscription.create(
                customer= user_membership.stripe_customer_id,
                items=[
                {
                    'plan': selected_membership.stripe_plan_id,
                },
            ],
            #source = token
            #expand=['latest_invoice.payment_intent'],
            )
            print(token)
            return redirect(reverse('memberships:update-transactions',
                        kwargs={
                                'subscription_id': subscription.id
                            }))

        except stripe.error.CardError as e:
            messages.info(request, "Your card has been declined!")


    context = {
    'publishKey': publishKey,
    'selected_membership': selected_membership
    }

    return render(request, "memberships/membership_payment.html", context)

def updateTransactions(request, subscription_id):
    user_membership = get_user_membership(request)
    selected_membership = get_selected_membership(request)
    user_membership.membership = selected_membership
    user_membership.save()

    sub, created = Subscription.objects.get_or_create(user_membership = user_membership)
    sub.stripe_subscription_id = subscription_id
    sub.active = True
    sub.save()
    try:
        del request.session['selected_membership_type']
    except:
        pass

    messages.info(request, "Successfully created {} membership".format(selected_membership))
    return redirect(reverse('memberships:select'))
    #return redirect('memberships/')

@login_required
def profile_view(request):
    user_membership = get_user_membership(request)
    user_subscription = get_user_subscription(request)
    daily_pick_content = get_daily_pick(request)
    context = {
        'user_membership': user_membership,
        'user_subscription': user_subscription,
        'daily_pick_content': daily_pick_content
    }
    #print(context)

    return render(request, "memberships/profile.html", context)

@login_required
def cancelSubscription(request):
    user_sub = get_user_subscription(request)
    user_membership = get_user_membership(request)

    if user_sub.active is False:
        messages.info(request, "You dont have an active membership")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    sub = stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
    sub.delete()

    user_sub.active = False
    user_sub.save()

    free_membership = Membership.objects.get(membership_type = 'Free')
    user_membership = get_user_membership(request)
    user_membership.membership = free_membership
    user_membership.save()


    messages.info(
        request, "Successfully cancelled membership. We have sent an email")
    # sending an email here

    return redirect(reverse('memberships:select'))

apps/memberships/templates/memberships/membership_detail.html
{% extends 'posts/base.html' %}

{% block membership_detail_link %}
<li>{{ object.title }}</li>
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-md-4">
				<h1>Membership Detail</h1>
				<h3>{{ object.title }}</h3>
				<p>{{ object.description }}</p>
				<ol>
					{% for lesson in object.lessons %}
					<li><a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a></li>
					{% endfor %}
				</ol>

			</div>
		</div>
	</div>

{% endblock %}

apps/memberships/templates/memberships/membership_list.html
{% extends 'posts/base.html' %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">

  {% block content %}
  <div class = 'container' >
    <h1>Select a Membership:</h1><br><br><br>

      <div class = "row">
        {% for object in object_list %}

          <div class = "col-sm-3 col-md-3">
            <div class="panel panel-default">
              <div class="panel-body">
              <h2>{{ object.membership_type }}</h2>
              <h3>{{ object.description}}</h3>
              <p>Price: ${{ object.price }}</p>

                <form method = "POST" action = "{% url "memberships:select" %}">
                  {% csrf_token %}
			             <button class="btn btn-warning">Select</button>
                    <input type = "hidden" name = "membership_type" value = "{{ object.membership_type }}">
                </form>
              </div>
              </div>
              </div>
              {% endfor %}
            </div>
          </div>

{% endblock content %}

apps/memberships/templates/memberships/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

apps/memberships/templates/memberships/profile.html
{% extends 'posts/base.html' %}


{% block content %}
	<div class="container">
		<div class="row">
			<div class = "header col-sm-4 col-md-4">
			<h1>My Profile </h1>
			</div>
			<div class = "header col-sm-6 col-md-6">
				<center>
						<h1>Pick of the Day!</h1>
				</center>
			</div>
		<div class="col-sm-4 col-md-4">
			{% if user_subscription != None %}
			<h4>Current Membership: {{ user_membership.membership.membership_type }} <medium> Member since {{ user_subscription.get_created_date }}</medium></h4>
				<h4>Next payment due:{{ user_subscription.get_next_billing_date }}</h4>
				<h4><a href="{% url 'memberships:select' %}"><mark>Upgrade Membership</mark></a></h4>
				<h5><a href="{% url 'memberships:cancel' %}">Cancel subscription</a></h5>
			{% else %}
			<p>You don't have an active membership plan. Check them out here:
				<a href="{% url 'memberships:select' %}">Select Membership</a>
			</p>
				{% endif %}
			</div>
			<div class = "col-sm-6 col-md-6">
				<center>
				<h4>{{ daily_pick_content.object.content }}</h4>
				</center>
			</div>
		</div>
	</div>
{% endblock content %}